services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"